### ISSUE TITLE
Allow ctx.refresh({ transparent: true })

### ISSUE THREAD

**Issue by aralroca** [guillotinaweb/guillotina_react#107]
after calling `ctx.refresh()` a progress bar is displayed and the screen is empty for a while, then it's rendering the data again with the new Guillotina object. 

I think is interesting to allow the option to refresh the Guillotina object underneath, being transparent to the user. 

Proposal: `ctx.refresh({ transparent: true })`

**Comment by jordic** [comment]
Seems legit to me!
