### ISSUE TITLE
Improve sensitive of searcher

### ISSUE THREAD

**Issue by aralroca** [guillotinaweb/guillotina_react#23]
Right now you can search only if the full searched word is exactly the same that the word that are you looking for. Is this done in this way for some reason? Or can it be improved? @jordic 

![searcher](https://user-images.githubusercontent.com/13313058/73479183-c6a44b00-4397-11ea-8819-189016ab8b58.gif)

**Comment by jordic** [comment]
There is an API on the guillotina side that allows to search on distinct fields and with distinct concordances... Right, there is a simple impl. That translates the search to the appropriate query on the postgres catalog. (For elastic it's right another history).. that said, you can do things like id=xxx title__in=cc number__gte=4.. but it depends on the fields you have indexed on your content-type, and the kind of index declared for them.. 

by default, if no field is provided it searches on title__in but we need to ensure that the default index is a text index.

**Comment by aralroca** [comment]
But why the default `title__in` is doing the same as `title__eq`?

With these items:

1. example
2. example2
3. example3

Doing the request `@search?title__in=example&b_start=0&b_size=10` is only returning the first item. I was expecting to get all three.

**Comment by jordic** [comment]
Perhaps @bloodbare, the API creator, can answer some of this.. his is also on charge of the pgcatalog

**Comment by bloodbare** [comment]
AFAIK its not API problem, the API is clear that `in` means match in the field and `eq` means equal match. Maybe is related on PGCatalog implementation: https://github.com/plone/guillotina/blob/master/guillotina/contrib/catalog/pg.py#L143 ?

**Comment by jordic** [comment]
Mmm.. the "?|" Should only be used with keyword fields.. for text fields I think it should be something like: 'ilike %xxx%'

**Comment by bloodbare** [comment]
@jordic I smell a PR ?

**Comment by jordic** [comment]
Closing because it's mostly a guillotina issue
